### ISSUE TITLE
Systemd notify services hangs indefinitely when TimeoutSec=0 due to problems with systemd-notify

### ISSUE THREAD

**Issue by djessich** [test-kitchen/dokken-images#35]
## :ghost: Brief Description

Starting a Systemd service of type `notify` hangs indefinitely when TimeoutSec=0 was specified. Systemd does not properly export the variable $NOTIFY_SOCKET, so Systemd does not see the notification and as a result it hangs indefinitely. However, this can be avoided by setting TimeoutSec to any positive value, but this will cause Systemd to finish and "think" the service was successfully started. The service process itself, does not notify Systemd successfully. As this is symptom handling, it does not represent a valid option.

This can be reproduced with PostgreSQL service. The service can be started without any problems in vagrant VM provided by Bento project.

## Version

Latest container dokken/centos-8.

## Environment

Chef Workstation: 20.9.158
Chef Client: 16.5.77
Inspec: 4.23.11
Test Kitchen: 2.7.2

## Scenario

It is not possible to start a Systemd service of type `notify`.

## Steps to Reproduce

1. Create new container dokken/centos-8
2. Install the PGDG repository RPM using `dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm`
3. Disable PostgreSQL module stream using `dnf -qy module disable postgresql`
4. Install PostgreSQL using `dnf install -y postgresql96-server`
5. Restart PostgreSQL using `systemctl restart postgresql-9.6`

## Expected Result

PostgreSQL restarts successfully using Systemd.

## Actual Result

PostgreSQL restart hangs indefinitely using Systemd. However, direct start of PostgreSQL starts without any problems, so this is no Bug in ProstgreSQL itself. It seems that `systemd-notify` does not work properly, due to any reason. It works in vagrant VM provided by Bento project.

## :heavy_plus_sign: Additional context

Executing the following command explicitly provides a hint to the problem.

```
[root@dokken /]# systemd-notify --ready
No status data could be sent: $NOTIFY_SOCKET was not set
```

The socket exists in path `/run/systemd/notify`.

Using container `dokken/centos-7` everything works as expected, the service `postgresql-9.6` is able to start successfully.

**Comment by tas50** [comment]
@djessich Give it a try with the latest containers after they build shortly and let us know if this is still a problem.
