### ISSUE TITLE
Ensure CentOS 8 images have a working systemd

### ISSUE THREAD

**Issue by clintoncwolfe** [test-kitchen/dokken-images#44]
## :speaking_head: Foreword

Recent `systemd` on CentOS 8 fail to report service status correctly with certain kernel versions - see https://bugzilla.redhat.com/show_bug.cgi?id=1901449  .

A fix has been released in CentOS 8 stream, systemd-239-44.el8.x86_64. Ensure that the CentOS 8 and CentOS 8 stream images contain at least that version. 

## Version

Current dokken/centos-8 image (b79efc2c7, 2021-02-23) contains systemd-239-41.

## :heavy_plus_sign: Additional context

https://github.com/inspec/inspec/issues/5398

**Comment by tas50** [comment]
Triggering all builds now

**Comment by tas50** [comment]
This update hasn't made it's way to centos 8 yet

**Comment by clintoncwolfe** [comment]
After internal discussion, we've concluded this is a fix that needs to be released by the CentOS 8 team. Once that happens, we'll cut new images, but we won't try to jam the fix from Stream into regular CentOS 8.

**Comment by tas50** [comment]
Closing since this relies on upstream changes that come in automatically (or don't)
