### ISSUE TITLE
Docker images versions?

### ISSUE THREAD

**Issue by zedtux** [test-kitchen/dokken-images#45]
### :speaking_head: Foreword

Thank for taking the time to fill this feature request fully. Without it we may not be able to , and the issue may be closed without resolution.

## :frowning_person: Problem Statement

I'm building a Chef cookbook which uses Docker, so I'd like to have the `docker` command available.

## :grey_question: Possible Solution

Would be great to:

* Either have a `-docker` version of the images which installs Docker and make it available with dokken
* Either install `docker` in each images

## :arrow_heading_up: Describe alternatives you've considered

I don't really see any yet.

## :heavy_plus_sign: Additional context

None

**Comment by damacus** [comment]
You can do this as part of the first command within the kitchen.yml

Adding docker to the images isn't something we're going to be doing as it'll add significant size to the images.
