### ISSUE TITLE
Remove Oracle Linux 6 when EOL

### ISSUE THREAD

**Issue by damacus** [test-kitchen/dokken-images#90]
Current EOL date is July 2024

**Comment by damacus** [comment]
@test-kitchen/maintainers I'm proposing we remove this given upstream hasn't released an update in 2 years

https://hub.docker.com/layers/library/oraclelinux/6/images/sha256-a06327c0f1d18d753f2a60bb17864c84a850bb6dcbcf5946dd1a8123f6e75495?context=explore

**Comment by Stromweld** [comment]
my .02 are to axe it and not go off oracle extended support. There extended support is in line with RHEL's Extended lifecycle support not their extended maintenance support. It's been removed from Bento for a while now and haven't seen any complaints for any rhel 6 variant. Rhel 7 is EOL in 10 months and most companies I've seen are well on the way to remove rhel 7 variants if not already there. The few stragglers can still download the old versions they just won't be maintained with latest updates and would simply have to do that themselves then. If there is evidence to show that it's still being heavily downloaded and used then it would make sense to keep maintaining it.

**Comment by Firefishy** [comment]
See https://github.com/test-kitchen/dokken-images/pull/100
